server:
  port: 8080

spring:
  application: 
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: 
    hibernate: 
      ddl-auto: update
  
  # Cloud Config Server 
  config:
    import: configserver:http://localhost:9296

# Zipkin and Slueth Configuration
management:
  tracing:
    sampling:
      probability: 1.0


# # Eureka Client Configuration - to conenct to Eureka Service Application
# eureka:
#   instance:
#     prefer-ip-address: true
#   client: 
#     fetch-registry: true
#     register-with-eureka: true
#     service-url:
#       defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

# The Above configuration is moved to git by Config Server 